version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: checkpoint_technical_app
    restart: unless-stopped
    ports:
      - ${PORT:-3001}:3001
    environment:
      - PORT=3001
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET:-Checkpoint_Systems_Technical_Key_2026_Secure!}
      # PostgreSQL Server Connection Variables (Kết nối container PostgreSQL có sẵn)
      - DB_HOST=${POSTGRES_HOST}
      - DB_PORT=${POSTGRES_PORT}
      - DB_USERNAME=${DB_USERNAME:-${POSTGRES_USER}}
      - DB_PASSWORD=${DB_PASSWORD:-${POSTGRES_PASSWORD}}
      - DB_NAME=${DB_NAME:-${POSTGRES_DB}}
      - DB_AUTO_INIT=${DB_AUTO_INIT}
    volumes:
      - ./data:/app/data
    networks:
      - iot_postgres_internal_net
      - dockge_default

networks:
  iot_postgres_internal_net:
    external: true
  dockge_default:
    external: true
